### ISSUE TITLE
Add link to Arxiv preprint

### ISSUE THREAD

**Issue by impredicative** [equinor/pylops#100]
Please mention and add a link to the corresponding Arxiv preprint https://arxiv.org/abs/1907.12349 into the readme of this repo.

**Comment by mrava87** [comment]
Will be included in the next PR :)

**Comment by mrava87** [comment]
Added now here https://pylops.readthedocs.io/en/latest/citing.html

**Comment by impredicative** [comment]
@mrava87 , no, you don't understand. The link is more important as a background reference for everyone than it is for citation purposes, maybe by a 100:1 ratio. That's why it should be mentioned and linked in the readme.

**Comment by mrava87** [comment]
Sorry I didn't understand, its done now
