### ISSUE TITLE
Bug in pylops.Kronecker

### ISSUE THREAD

**Issue by RendersJens** [equinor/pylops#125]
The implementation of the Kronecker product in pylops.Kronecker is faulty. As a demonstration, I compute the Kronecker product of 2 simple matrices, using numpy.kron, and compare it to the same product with pylops.Kronecker:
```
import pylops
import numpy

A = numpy.array([[1.0, 0.0],
                 [1.0, 1.0]])

B = numpy.array([[1.0, 0.0],
                 [0.0, 1.0]])

print(numpy.kron(A,B))
print(pylops.Kronecker(pylops.MatrixMult(A),
                       pylops.MatrixMult(B)) @ numpy.eye(4))
```
The results is are different:
```
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 1. 0. 0.]
 [0. 0. 1. 1.]]
```
To get a correct implementation, the matrix `y` should be transposed before it is raveled (both in `_matvec` and `_rmatvec`), and the role of Op1 and Op2 should be switched in `_matvec` only. The resulting correct implementation is

```
def _matvec(self, x):
    x = x.reshape(self.Op1.shape[1], self.Op2.shape[1])
    y = self.Op1.matmat(x).T
    y = self.Op2.matmat(y).T.ravel()
    return y
def _rmatvec(self, x):
    x = x.reshape(self.Op1.shape[0], self.Op2.shape[0])
    y = self.Op1H.matmat(x).T
    y = self.Op2H.matmat(y).T.ravel()
    return y
```
Indeed, the implementation of `_rmatvec` should be identical to that of `_matvec` except for using the adjoint operators, Because taking the adjoint does not switch the order of the Kronecker product: `(AxB)^H = A^H x B^H`

**Comment by mrava87** [comment]
Hi, thanks a lot for reporting this :) It was clearly a mistake and my bad for not having a test checking the result versus numpy.

I tried your example and indeed it works with the new implementation. I just modified it a bit as I think square matrices with 1 and 0 do sometimes lead to good results and then when you try non-square with other numbers things may break down, but it is not the case here :) :
```
import pylops
import numpy

A = numpy.array([[1.0, 0.0],
                 [1.0, 1.0]])

B = numpy.array([[1.0, 0.0],
                 [0.0, 1.0]])

Kop= pylops.Kronecker(pylops.MatrixMult(A), pylops.MatrixMult(B))
pylops.utils.dottest(Kop, Kop.shape[0], Kop.shape[1], verb=True)


y=numpy.kron(A,B)
y1= Kop @ numpy.eye(4)
print(y)
print(y1)
print(numpy.allclose(y, y1))


A = numpy.array([[1.0, 2.0, 4.0],
                 [1.0, 3.0, 6.0]])
B = numpy.array([[4.0, 0.0],
                 [0.0, 6.0],
                 [2.0, 6.0],
                 [-3.0, 5.0]])
y =numpy.kron(A, B)

Kop= pylops.Kronecker(pylops.MatrixMult(A), pylops.MatrixMult(B))
pylops.utils.dottest(Kop, Kop.shape[0], Kop.shape[1], verb=True)

y1= Kop @ numpy.eye(6)
print(y)
print(y1)
print(numpy.allclose(y, y1))
```

I was however a bit puzzled as both numpy doc and pylops doc explain the Kronecker product the same way 
```
[[ a[0,0]*b,   a[0,1]*b,  ... , a[0,-1]*b  ],
 [  ...                              ...   ],
 [ a[-1,0]*b,  a[-1,1]*b, ... , a[-1,-1]*b ]]
```
for numpy, and our equation here https://pylops.readthedocs.io/en/latest/api/generated/pylops.Kronecker.html#pylops.Kronecker. 

The implementation of pylops tried to follow the equation but even if it passed the dot test it was clearly wrong as you showed. Your implementation does in a way deviate from the equations, which is not a big problem as long as the documentation is changed accordingly.

Looking back at the original implementation, I find that these changes also lead to the correct results:
````
def _matvec(self, x):
        x = x.reshape(self.Op1.shape[1], self.Op2.shape[1])
        y = self.Op2.matmat(x.T).T
        y = self.Op1.matmat(y).ravel()
        return y

    def _rmatvec(self, x):
        x = x.reshape(self.Op1.shape[0], self.Op2.shape[0])
        y = self.Op2H.matmat(x.T).T
        y = self.Op1H.matmat(y).ravel()
        return y
````
I think your one may be faster has it has less `.T` but I would still like to investigate a bit more why both work and if any of the two breaks in any special case. 

Do you want to make a PR and change the docstring accordingly to the implementation or you prefer me to do it. Either way is fine by me and I really appreciate that you reported this bug :)

**Comment by RendersJens** [comment]
I think both implementations are identical in terms of speed (both use `.T` twice). I prefer you to make the changes as I have no experience with this. Thank you for your swift response as always :)

**Comment by mrava87** [comment]
Great :) I will make changes then. Thanks a lot for reporting this

**Comment by mrava87** [comment]
Bugs should be fixed. I have also changed the docstring accordingly to the implementation. Please report back if you still experience any problem :)
