### ISSUE TITLE
Marchenko redatuming 

### ISSUE THREAD

**Issue by lily1023** [equinor/pylops#149]
Hi, thank you guys for providing these good algorithms for us to do research. 

I am a student majoring in geophysics, I am using your Marchenko redatuming python code. After I changed the virtual source locations, the Green's function the code produced is incorrect. 

I think the parameter trav has changed with the virtual source location, but the function MarchenkoWM.apply_onepoint may need to fix. Could you please check and fix it? 

Thank you for your help. I am looking forward to your reply.
Stay safe!
Mengli

**Comment by mrava87** [comment]
Hi Mengli,
nice to hear you find our library useful for your research :)

You should have got a longer reply to your email.  Just for the record, I think the problem arises from the fact that you may not change ``G0`` when changing the location of the virtual source and so the traveltime. Try to take a look at this notebook https://github.com/mrava87/pylops_notebooks/blob/master/developement/Marchenko.ipynb where the ``Marchenko.apply_onepoint`` routine is applied - specifically under the following text ``
Finally we show that is also possible to use an analytical direct wave``. Here you can change virtual point location, compute directVS with the new point and feed it to the ``apply_onepoint`` routine. The output will be the wavefields from the new virtual point :)

I also strongly recommend using ``apply_multiplepoints`` as in the example below in the same notebook. You will get great speed-up compared to doing one point at the time.

Let me know how it goes :)

**Comment by mrava87** [comment]
Hi,
I was just wondering if you solved your problem 

Shall I close this issue?

**Comment by lily1023** [comment]
Hi, Matteo,

Thank you so much! Yes, this problem has been solved after receiving your detailed email!

I really appreciate your help!
All the best,
Mengli



Sent from my iPhone

On May 14, 2020, at 7:35 AM, Matteo Ravasi <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
I was just wondering if you solved your problem

Shall I close this issue?
