### ISSUE TITLE
Set up difference scheme in Gradient/FirstDerivative

### ISSUE THREAD

**Issue by lucasplagwitz** [equinor/pylops#158]
By using Gradient Operator for Total Variation denosing in my project I got some artifacts in the solution. If I define my own sparse version it is fine. 
You are using central differences in Gradient/FirstDerivative. With wikipedia 'oscillating functions can yield zero derivative', a working Gradient with backward differences and my desired solution of piecewise constant TV/BV functions, I think of central differences as my problem.

Is there a way of setting the difference scheme? Or would you implement a parameter for this in pylops future versions?

**Comment by mrava87** [comment]
Hi @lucasplagwitz,
thanks a lot for filing the issue.

You are correct, currently all derivatives (FirstDerivative and SecondDerivative) are currently centered. But it should be easy to provide alternative options (forward or backward and also higher order) if there is a specific reason/need. 

Would you mind pointing me to the webpage you refer to as `wikipedia 'oscillating functions can yield zero derivative'` and your code where you have `my desired solution of piecewise constant TV/BV functions`. If I understand correctly what you say is that a backward (instead of centered) derivatives works better?

If I can see how you make your sparse matrix it should be pretty straightforward to write its equivalent linear operator :)

**Comment by mrava87** [comment]
Just to be clear, you use the Accuracy=1 of backward derivative as in https://en.wikipedia.org/wiki/Finite_difference_coefficient ? Or higher accuracy?

**Comment by lucasplagwitz** [comment]
Thanks for your prompt response. Wikipedia page was: https://en.wikipedia.org/wiki/Finite_difference on subsection Relation with derivatives and you can see my integration of Gradient as example here: https://github.com/lucasplagwitz/recon/blob/master/recon/reconstruction/pd_smooth.py

In line 50 I switch between dimensions, cause I only implement my sparse Gradient for 2d and want to use your package here. When I use your Gradient my solutions changes:
**Sparse Gradient**
![sparse_gradient](https://user-images.githubusercontent.com/23482575/84030520-803da900-a994-11ea-9b86-04b9f3e94d2e.png)

**pylops Gradient**
![pylops gradient](https://user-images.githubusercontent.com/23482575/84030581-96e40000-a994-11ea-8b50-6daa51ecaef6.png)

Do you see the pixel error?
As I mentioned before I am not completely sure.

**Comment by mrava87** [comment]
Fantastic, thanks a lot!

I see what you mean in your code having your sparse version for 2d and pylops Gradient for 3d. Let me have a go at changing FirstDerivative/SecondDerivative to allow also for forward and backward derivatives and add a parameter for choosing which to use... all the other operators should fall into place the same way :)

I will keep you posted here, i dont think it should take too long to have a working version, then we can try your example and see if that is what fixes this bad pixelation :)

**Comment by lucasplagwitz** [comment]
Very nice support! Thanks a lot, I'm curious.

**Comment by mrava87** [comment]
Hi again,
I think I managed to implement both forward and backward derivatives but I would like to check something with you first.

I tried to take some lines from your routine  in https://github.com/lucasplagwitz/recon/blob/master/recon/reconstruction/pd_smooth.py and look at your sparse matrices. What I see when I display them (correct me if I did something wrong) is:

![orig_der](https://user-images.githubusercontent.com/22675848/84068211-e93f1400-a9c8-11ea-8f5a-0f0f06e7d436.png)

I am not sure how to interpret them as they seem to point in opposite directions (apart from being shifted to each other by one sample)  Following the wikipedia definition (or at least thats what I think) I would say that the matrix should look like this:

![mod_der](https://user-images.githubusercontent.com/22675848/84068310-0d025a00-a9c9-11ea-8f94-1be425aece90.png)

where both forward and backward apply the derivative along the positive x axis (from left to right) and they are just shifted (but both have the -1 1 stencil)

If I implement the Linear operators following wikipedia you could always get your definition by using forward in one case (`dy`) and -forward in the other (`dx`), but would be good to make sure we agree on the definitions before I merge the code :)

**Comment by lucasplagwitz** [comment]
I totally agree, you are right. Sorry, my Derivate is -1 shifted. In my case it shouldn't matter cause I always use norm(Gradient). 
I'm looking forward to the merge!

**Comment by mrava87** [comment]
Perfect! Hopefully today I get some time to wrap things up and merge it - so far I have done the FirstDerivative which is what I think you need looking at your code, I will do SecondDerivative after and merge it in a second moment :)

**Comment by mrava87** [comment]
Heya,
I just merged the changes. You will see that `FirstDerivative` has now a new input parameter called `kind` that can be chosen as explained here https://github.com/equinor/pylops/blob/cecf48c8f8541a7026a214f4bdd4237e9db20594/pylops/basicoperators/FirstDerivative.py#L26 Similarly other operators like `Gradient` and `FirstDirectionalDerivative` has the same parameter.

As you can see at the end of this notebook (https://github.com/mrava87/pylops_notebooks/blob/master/developement/Derivative.ipynb) I compared the result with the modified sparse matrix definitions and they are identical. It would be great if you can try again running your sparse inversion and see if the results do agree with those from sparse matrices :)

**Comment by lucasplagwitz** [comment]
It works! backward and forward runs without that oscillation error and with centered it occurs.
Very nice and fast work. Now I can fully switch to pylops - thanks a lot!

**Comment by mrava87** [comment]
Amazing! I’m glad you figure out where the problem was, I am going to wait and see how you used it when you push your code and then do the same for some of our examples when we use TV regularization :)

**Comment by mrava87** [comment]
Btw, I am very interest in your reconstruction+segmentation solver and I think it may have wider applicability than medical imaging :)

Would you be interested to work together on incorporating it within PyLops? There are a few things to consider but I think neither of them is a real show stopper:

- license: I see that the original matlab code you based your work from has no license. Your recon is GPL though. To be able to take a part of your code and include it in PyLops we would need some sort of written ‘agreement’ that the author of the code is happy to have some of his code taken by a LGPL project, but I guess if you agree that’s easy as saying that in a PR
- function based: so far our solvers are function based. There has been some discussion/plan to switch to class based definition in v2 but I’m not sure when this will happen. I see some of your solvers are classes but I guess it should be double to adapt them.

Of course this is just a suggestion, no pressure. And your project looks awesome, very happy to see also the medical imaging community is using python more and more ;)
