### ISSUE TITLE
Replace np.fft routines with pyFFTW

### ISSUE THREAD

**Issue by mrava87** [equinor/pylops#20]
For speeding up routines involving fft pyFFTW (https://github.com/pyFFTW/pyFFTW) may be a good choice. 

It comes with an extra dependency and will leave the user with the manual installation of FFTW as described in pyFFTW manual, but it has wrappers to numpy/scipy fits, so we could fallback to bumpy if FFTW is not available.

**Comment by prisae** [comment]
If I am not mistaken FFTW is not in `scipy` because of the license. So you will have to make the user install it on its own and provide a fallback-option, I guess. Not sure though.

**Comment by mrava87** [comment]
Correct user will have to install FFTW. My initial thoughts are that more HPC oriented libraries (pyfftw, numba, pycuda, Adam) will be eventually used but we should always have fallbacks to basic libraries (numpy-scipy).

For example here we could have a private class _FFT_numpy and one _FFT_fftw and then a function FFT creating the correct operator based on user flag + check that pyfftw can be imported. Just an idea, maybe there is even a better way?

All said, the condition for pyfftw to be included is that we can have a travis build able to install FFTW and do tests on the FFT operators (that should be doable as pyfftw does it itself), if so I would say pyfftw should be used as fft is at the core of many operators (and run 100-200 times during an inversion with iterative solvers)

**Comment by mrava87** [comment]
Close this as a double backend was added in this PR https://github.com/equinor/pylops/commit/91ac04718ea50a9c3ea4b27472186ee6375d6f3f
