### ISSUE TITLE
Add docs-url to header.

### ISSUE THREAD

**Issue by prisae** [equinor/pylops#48]
Just a personal preference. I like when the link to the main page is straight next to the title. Often I end up on the GitHub-site but I actually want the docs, so I appreciate this shortcut.

With the example of empymod:
![2019-02-05_01](https://user-images.githubusercontent.com/8020943/52312746-478d5a00-2971-11e9-8f8b-f77d4925d7c5.jpg)

Which, in this case, would be https://pylops.readthedocs.io.

**Comment by mrava87** [comment]
Makes sense. There is a badge and a link in the README but it’s good idea to have it up the top :)
