### ISSUE TITLE
Discrepancy between pip and repo

### ISSUE THREAD

**Issue by Gouber** [equinor/pylops#94]
Sys - win10
pip - 19.1.1
python 3.7.3

Installed pylops using pip and when I opened the mdd.py file installed under \lib\site-package\pylops I noticed that the definition of MDD is different to the one in this repo. The example "08. Multi-Dimensional Deconvolution" seems to only work with the version that you get from pip and if you try to use the version of the function on this repo it complains about dimension error. The significant difference is on line 251. The repo version seems to transform the array before calling the MDC whereas the pip version just calls the MDC.

**Comment by mrava87** [comment]
Hi,
thanks for the issue.

Yes, you are correct. Changes were made to the mdd.py file in this PR https://github.com/equinor/pylops/commit/c9b7cd8a779b2721bd5918523bd5332ab2a431be.

The inner working is changed but the API should be working in the same way, meaning if you run a code written prior to this PR that should give same results. This is the case for the tests and example you refer to but if you encounter a problem please report it with a snippet of your code so I can understand where things break. Just for you to know, the change in the inner working makes this operator faster as detailed in https://pylops.readthedocs.io/en/latest/api/generated/pylops.waveeqprocessing.MDC.html#pylops.waveeqprocessing.MDC but the MDD routine does everything for you under the hood as you have noticed.

Note that there will be a new release 1.5.0 in coming weeks and then the code in repo will agree with the one you get from pip install. If you look at the mdd.py code in v1.4.0 tag (not in master) https://github.com/equinor/pylops/blob/v1.4.0/pylops/waveeqprocessing/mdd.py that should agree with what you see from pip.

**Comment by mrava87** [comment]
Can you confirm from where you get The example "08. Multi-Dimensional Deconvolution", https://pylops.readthedocs.io/en/latest/tutorials/mdd.html#sphx-glr-tutorials-mdd-py or https://pylops.readthedocs.io/en/stable/tutorials/mdd.html#sphx-glr-tutorials-mdd-py? Note the ``latest`` vs ``stable`` in the URL. 

The way the documentation works, it should be that the stable works with pip and latest with the code in master branch. If this is not the case I can try to reproduce your error locally and fix the tutorial. When you say ``The significant difference is on line 251`` you mean in the tutorial file or in the actual mdd.py file?

**Comment by Gouber** [comment]
Ah I see. I didn't realize there were 2 versions and I tried using the mdd and mdc definitions from the latest version (the one in git) while having the pip version installed.

**Comment by mrava87** [comment]
No problem. Always refer to the stable doc if using pip version and latest doc if using master. This is a general rule for every package.
Thanks for reporting :)
