### ISSUE TITLE
MDC chained operator

### ISSUE THREAD

**Issue by Gouber** [equinor/pylops#96]
After reading the paper quoted, I did not find any explanation in regards with  F^(H)GF (does the paper itself explain it or one of referenced papers?). I'm assuming the idea is to create an object that holds a copy of one of the data sets and whenever you call `MDC.*` you perform convolution between the copy held by the object and the argument to the function. (I might be misunderstanding?).  Could you provide a quick alternative in pylops to the following matlab code?

```

A(:,:,1) = [1,2,1;2,3,0];
A(:,:,2) = [3,2,2;1,2,3];

B(:,:,1) = [1,1;1,1];
B(:,:,2) = [1,1;1,1];



convn(A,B)
```
When trying to write the alternative I wasn't certain what values `nt` and `nv` should be. Also, I know the result will be another operator so is there a way to actually display the result of the convolution?

**Comment by mrava87** [comment]
Hi,
the paper referred to in the documentation is the most cited paper for this type of techinique in geophysics. Their implementation is however in the frequency domain and they do not perform  F^(H)GF, I can add a second, less popular reference (see link https://academic.oup.com/gji/article/192/2/666/2030635) that actually implements the operator in the same way we do here.

You are right, the ``MDC`` operator has a variable that points to the kernel ```G`` of the multi-dimensional convolution equation, and ``A* x`` applies that operator to an input vector ``x`` using the kernel you have provided. You can indeed chain two ``MDC`` operators (``C = A*B``), they will never be 'multiplied' themselves, but when you apply the resulting ``C`` to a vector (``C* x``), it will first apply ``A`` to ``x`` and subsequently ``B`` to the result of ``A * x``.

I am not sure what your refer to as ``convn`` in matlab is the same as our ``MDC`` as this operator is a special kind of Fredholm integral (https://en.wikipedia.org/wiki/Fredholm_integral_equation) for each frequency slice. 

What you ask is a simple N-dimensional convolution, so far this is not present in pylops (we have https://pylops.readthedocs.io/en/latest/api/generated/pylops.signalprocessing.Convolve1D.html#pylops.signalprocessing.Convolve1D and https://pylops.readthedocs.io/en/latest/api/generated/pylops.signalprocessing.Convolve1D.html#pylops.signalprocessing.Convolve2D) but that should be easy to add. I will give it a go and use your example to compare results.

**Comment by Gouber** [comment]
Hi,
I appreciate the quick response :)

I might have confused the actual use of MDC and MDD then. I was under the impression that MDD reverses the effect of multidimensional convolution ( `C = convn(A,B)` in matlab). So if I had A,B and C defined as above and I outputted `minv` where `minv = MDD(B,C)` I'd expect C (or something close to it)? Is the behavior completely different?

**Comment by mrava87** [comment]
Yes and no, I think it is just some confusion in the nomenclature.

The matlab ``convn`` is something I would call Nd-convolution while multi-dimensional convolution is something different which is used by the geophysics community.

When I implement the ``ConvolveND``` operator mimicking the matlab ``convn``, what you say will become possible: you can invert a Ndimensional compact filter (3 dimensional in your example) by simply doing ``B \ C`` where B is the operator that applies this 3d filter, and C is the blurred data.

If I understand correctly this is what you are after but in one more dimension https://pylops.readthedocs.io/en/latest/tutorials/deblurring.html#sphx-glr-tutorials-deblurring-py, isn't it?

**Comment by Gouber** [comment]
Hey,

My end goal is understanding MDD and I wasn't entirely sure what MDC did.  [Here](https://github.com/equinor/pylops/blob/d358a2793c2c35a8e5608de79683c2abf1022105/pylops/waveeqprocessing/mdd.py#L346) you find the least squared solution to an MDC object and `G` but I struggle to see how that's equivalent to the psf defined as D'D.

**Comment by mrava87** [comment]
Ok, in that case I recommend to read the paper mentioned in the documentation and the one I referred to in previous comment. They contain all needed theory to understand what MDC (the modelling operator) and MDD (the inverse process) do in this library and both nomenclature and equations should be consistent with each other.

Inverting the PSF is a special check used to understand the ill-positioning of the problem. If the problem can be solved then the result of inverting the PSF will give you a delta spike in time and space as in the tutorial example.

**Comment by mrava87** [comment]
Added now ConvolveND (https://github.com/equinor/pylops/commit/8948ccc855585a31dc49ed0ecadd9b937b369e44) to allow convolution with N-dimensional compact filters. Take a look at https://pylops.readthedocs.io/en/latest/gallery/plot_convolve.html#sphx-glr-gallery-plot-convolve-py for an example.

I understand you may be more after but if you ever need to use something like Matlab  convnd, ConvolveND will give you both forward and adjont of that operation.
