### ISSUE TITLE
Trivial block diag operator

### ISSUE THREAD

**Issue by vnis5001** [equinor/pylops#97]
Hi, I'm kind of struggling to get to grips with the operator logic. I have the following code:
```
A = np.array([[1,0],[0,1]])
I1 = MatrixMult(A)
I2 = MatrixMult(A)
I3 = MatrixMult(A)
BOp = BlockDiag(op_list)
```

According to my understanding I'd assume any matrix that has 3 rows will have the identity matrix applied to every element of it. So if every element is another matrx such as follows:

```
X = np.array([[[2,3],[3,2]],[ [4,5],[5,5]],[[6,6],[0,1]]])
```

I'd expect `[[2,3],[3,2]] * [[1,0],[0,1]]` to be placed into the first row, first column of my result matrix however a dimension error is thrown. Where is the flaw in my logic?

Thanks

**Comment by vnis5001** [comment]
https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorBlockDiag explains the use but also it seems that this operator only supports multiplication by a multiple row - one column matrix

**Comment by mrava87** [comment]
Hi,
thanks for the issue.

I am not sure I understand what you are trying to do, can you add a piece of working code so I can reproduce it. For example I don’t know how op_list is created above.

In general any operator (like your Bop above) can be applied to a vector/or matrix via matvec (or *) or matmat respectively. In your case as X is a matrix you would need to do Bop.matmat(X)

However as you say that you want to multiply by an Identity, I suggest to use directly the Identity operator as it is much more efficient than using MatrixMult for this specific task
