### ISSUE TITLE
Fredholm1 operator

### ISSUE THREAD

**Issue by vnis5001** [equinor/pylops#98]
Hey,

I've created a 6x9 Fredholm1 operator from the following array

```
G = np.array([ [[2,1,0],[0,5,1]],[[2,3,1],[0,2,1]],[[3,1,2],[2,3,4]] ])
#G.shape => 3x2x3
Gop = Fredholm1(G)
#Gop.shape => 6x9

```
What should the shape of `X` be if I want to perform `G * X` ?

**Comment by Gouber** [comment]
+1
You can multiply it by an identity of N = 3*3 but can't quite figure it out for any actual data?

**Comment by mrava87** [comment]
Hi,
sorry for the slow reply.

Any operator in this library shares the same logic. It is equivalent to a matrix `G` of shape `G.shape` and operates in forward mode on of input model vectors of size `G.shape[1]` and  in adjoint mode on of input data vectors of size `G.shape[0]`.

In this specific case, the operator performs a repeated matrix-matrix multiplication (or multi-dimensional Fredholm integral) using https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html. You can also see this as a batched matrix multiplication if you are more familiar with ML type of linear algebra.

Here is a small working code:
```
Gop = Fredholm1(G, usematmul=False)
print(Gop)
y = Gop * np.ones(9)
x = Gop.H * np.ones(6)
```

I have realised that in the case of `nz=1` like you have, the implementation with `usematmul=True` gave an error. Try using `usematmul=False` for the moment and I am going to make a small PR in coming days which will also fix the implementation with `usematmul=True`

**Comment by mrava87** [comment]
This is fixed here https://github.com/equinor/pylops/commit/b3147dea6923dd9ad6c043c69fdc48762d619367.  The code snippet above should now also work with usematmul=True. 

Please let me know if everything works as expected from your side (installing Pylops from the master git version) and I will then create a new release with this and other changes

**Comment by mrava87** [comment]
I assume this is fixed, if you encounter any problem please just comment and reopen the case.
